FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

COPY smart_attendence_system-4 /app
WORKDIR /app

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]
