spring.application.name=smart_attendence_system-1

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5433/smart_attendance_db4
spring.datasource.username=postgres
spring.datasource.password=4518
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true